AWSTemplateFormatVersion: "2010-09-09"
Description: Secrets Manager secret created once and reused later

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prd]

  ProjectName:
    Type: String

Resources:
  ProjectSecrets:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    Properties:
      Name: !Sub "${ProjectName}-${Environment}"
      Description: !Sub "Secrets for ${ProjectName}-${Environment}"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Env
          Value: !Ref Environment

Outputs:
  SecretName:
    Value: !Ref ProjectSecrets
    Export:
      Name: !Sub "${Environment}-${ProjectName}-SecretName"

  SecretArn:
    Value: !Ref ProjectSecrets
    Export:
      Name: !Sub "${Environment}-${ProjectName}-SecretArn"
