AWSTemplateFormatVersion: "2010-09-09"
Description: Outputs-only stack for existing secret

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prd]

  ProjectName:
    Type: String

  SecretArn:
    Type: String
    Description: Full ARN of the pre-existing secret

Resources:
  DummyResource:
    Type: AWS::CloudFormation::WaitConditionHandle

Outputs:
  SecretArn:
    Value: !Ref SecretArn
    Export:
      Name: !Sub "${Environment}-${ProjectName}-SecretArn"

  SecretName:
    Value: !Sub "${ProjectName}-${Environment}"
    Export:
      Name: !Sub "${Environment}-${ProjectName}-SecretName"
