AWSTemplateFormatVersion: "2010-09-09"
Description: Internet Gateway and NAT Gateway

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prd]

  ProjectName:
    Type: String

  VpcId:
    Type: AWS::EC2::VPC::Id

  SubnetPublic1Id:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet for NAT Gateway (usually public subnet 1)

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-${ProjectName}-igw"

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VpcId
      InternetGatewayId: !Ref InternetGateway

  NatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEIP.AllocationId
      SubnetId: !Ref SubnetPublic1Id
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-${ProjectName}-nat"

Outputs:
  InternetGatewayId:
    Value: !Ref InternetGateway
    Export:
      Name: !Sub "${Environment}-${ProjectName}-InternetGatewayId"

  NatGatewayId:
    Value: !Ref NatGateway
    Export:
      Name: !Sub "${Environment}-${ProjectName}-NatGatewayId"

  NatEip:
    Value: !Ref NatEIP
    Export:
      Name: !Sub "${Environment}-${ProjectName}-NatEip"
